# This is a config for E2B sandbox template.
# You can use template ID (bkh4hi0uhzv7dz1bkupi) or template name (lamp-nextjs-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lamp-nextjs-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("lamp-nextjs-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lamp-nextjs-test2')

team_id = "4d3783f2-ca87-4ce2-a283-8b809ac4d0a0"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "test"
template_id = "bkh4hi0uhzv7dz1bkupi"
